apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - stage: dev
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: 'kargo-demo-{{ .stage }}'
      annotations:
        kargo.akuity.io/authorized-stage: 'kargo-demo:{{ .stage }}'
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/bjss/lunch-and-learn-argocd-playground.git
        targetRevision: 'kargo/stages/{{ .stage }}'
        path: 'apps/stages/{{ .stage }}'
      destination:
        name: 'in-cluster'
        namespace: 'kargo-demo-{{ .stage }}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
