# Kind - https://kind.sigs.k8s.io/docs/user/ingress/
controller:
  kind: DaemonSet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: NodePort
  watchIngressWithoutClass: true

  tolerations:
  - key: tier
    operator: Equal
    value: cd
    effect: NoSchedule

  publishService:
    enabled: false
  extraArgs:
    publish-status-address: localhost
