kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    tier: cd
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 80
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  labels:
    tier: app
