apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-demo-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bjss/lunch-and-learn-argocd-playground.git
      revision: argo-demo
      directories:
      - path: apps/stages/*
  template:
    metadata:
      name: 'argo-demo-{{ .path.basename }}'
    spec:
      project: argo-demo
      source:
        repoURL: https://github.com/bjss/lunch-and-learn-argocd-playground.git
        targetRevision: argo-demo
        path: '{{ .path.path }}'
        kustomize:
          namePrefix: 'argo-demo-{{ .path.basename }}-'
          images:
          - nginx=nginx:1.27
          commonLabels:
            app-env: '{{ .path.basename }}'
          commonAnnotationsEnvsubst: true
          commonAnnotations:
            app-source: ${ARGOCD_APP_NAME}
      destination:
        name: 'in-cluster'
        namespace: 'argo-demo-{{ .path.basename }}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
