apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-demo
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Demonstration of Argo CD
  sourceRepos:
  - 'https://github.com/bjss/lunch-and-learn-argocd-playground.git'
  destinations:
  - name: in-cluster
    namespace: argo-demo-*
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
