global:
  nodeSelector:
    tier: cd
  tolerations:
  - key: tier
    operator: Equal
    value: cd
    effect: NoSchedule
api:
  host: kargo.dev.local
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls:
      enabled: true
      selfSignedCert: true
    pathType: ImplementationSpecific

  adminAccount:
    ## @param api.adminAccount.enabled Whether to enable the admin account.
    enabled: true
    tokenTTL: 24h

  argocd:
    ## @param api.argocd.urls Mapping of Argo CD shards names to URLs to support deep links to Argo CD URLs. If sharding is not used, map the empty string to the single Argo CD URL.
    urls:
      "": https://argocd.dev.local:8443

  ## All settings relating to the use of Argo Rollouts by the API Server.
  rollouts:
    ## @param api.rollouts.integrationEnabled Specifies whether Argo Rollouts integration is enabled. When not enabled, the API server will not be capable of creating/updating/applying AnalysesTemplate resources in the Kargo control plane. When enabled, the API server will perform a sanity check at startup. If Argo Rollouts CRDs are not found, the API server will proceed as if this integration had been explicitly disabled. Explicitly disabling is still preferable if this integration is not desired, as it will grant fewer permissions to the API server.
    integrationEnabled: true
